import socket

COMMUNICATION_PORT = 5001  # Seems like we can use the same for all sockets :P

UNICAST_PORT = 5001

BROADCAST_ADDRESS = "192.168.0.255"
BROADCAST_PORT = 5000
BROADCAST_INTERVAL = 3

SERVER_GROUP_BASE_MULTICAST_ADDRESS = "224.1.1.1"
SERVER_GROUP_MULTICAST_PORT = 5002

BUFFER_SIZE = 4096 * 2

HEARTBEAT_INTERVAL = 2
HEARTBEAT_MAX = 6

HEADER_DELIMITER = "|"
PAYLOAD_DELIMITER = ":"
MAX_BROADCAST_RETRIES = 1

DEBUG = True
HEARTBEAT = False
